<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Product_OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_OrderRepository extends EntityRepository
{
}
