# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    
    admin.user:
        class: ShopBundle\Admin\UserAdmin
        arguments: [~, ShopBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
    
    admin.section:
        class: ShopBundle\Admin\SectionAdmin
        arguments: [~, ShopBundle\Entity\Section, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Section }
    
    admin.category:
        class: ShopBundle\Admin\CategoryAdmin
        arguments: [~, ShopBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }
            
    admin.product:
        class: ShopBundle\Admin\ProductAdmin
        arguments: [~, ShopBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Product }